#!/bin/bash

# Make requires like items.workspaces / colors resolve regardless of cwd
export LUA_PATH="$HOME/.config/sketchybar/?.lua;$HOME/.local/share/sketchybar_lua/?.lua;;"
export LUA_CPATH="$HOME/.local/share/sketchybar_lua/?.so;;"

exec lua "$HOME/.config/sketchybar/init.lua"
